engines:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 20
ratings:
  paths:
  - "**.js"
exclude_paths:
- "server/src/api/v1/tests/"
- "node_modules/"
- "template/"
- "server/dist/"
- "client/node_modules/"
- "server/src/docs/"
