language: node_js
node_js:
  - node
before_script:
  - npm install -g codeclimate-test-reporter
script:
  - npm test
after_success:
  - CODECLIMATE_REPO_TOKEN=CODECLIMATE_TOKEN codeclimate-test-reporter < coverage/lcov.info
env:
  - DB=postgresql
services:
  - postgresql
before_script:
  - npm install -g sequelize
  - psql -c 'create database travis;' -U postgres
script:
  - sequelize db:migrate --env production
