language: node_js
node_js:
  - node
services:
  - postgresql
before_script:
  - npm install -g codeclimate-test-reporter
  - npm run test:db
script:
  - npm test
after_success:
  - CODECLIMATE_REPO_TOKEN=CODECLIMATE_TOKEN codeclimate-test-reporter < coverage/lcov.info