language: node_js
node_js:
  - node
env:
  - TEST_DIR=server
notifications:
  email: false
services:
  - postgresql
before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g sequelize
  - psql -c 'drop database if exists travis;' -U postgres
  - psql -c 'create database travis;' -U postgres
  - |
    if[$TEST_DIR=="server"]; then
      npm run build;
    fi
  - NODE_ENV=test npm run test:db
script:
  - cd $TEST_DIR && npm test
after_success:
  - CODECLIMATE_REPO_TOKEN=CODECLIMATE_TOKEN codeclimate-test-reporter < coverage/lcov.info